name: Smyths API Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smyths-api-test:
    runs-on: ubuntu-latest

    steps:

      - name: Repository herunterladen
        uses: actions/checkout@v5

      - name: Python einrichten
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Playwright installieren
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Smyths Inventory API testen
        run: |
          python smyths_api_test.py
